/**
 * Storage abstraction for MinIO / S3-compatible object storage.
 *
 * S3_ENDPOINT is an *internal* address (e.g. Coolify's internal MinIO
 * service DNS) — it is never reachable from the browser and must never be
 * used to build a URL that gets sent to a client. Browser-facing URLs are
 * generated by getPublicUrl() as same-origin `/api/media/<key>` links,
 * served by src/app/api/media/[...key]/route.ts, which is the only thing
 * that talks to S3_ENDPOINT on the browser's behalf.
 *
 * Required environment variables:
 *   S3_ENDPOINT    MinIO or S3 endpoint, e.g. http://minio.internal:9000
 *   S3_BUCKET      Bucket name, default: invitesaas
 *   S3_ACCESS_KEY  Access key ID
 *   S3_SECRET_KEY  Secret access key
 *   S3_REGION      Region string, default: us-east-1
 *
 * Optional:
 *   MEDIA_PUBLIC_BASE_URL  Only needed if a CDN sits in front of this app on
 *                          a *different* origin. Unset (the normal case):
 *                          getPublicUrl() returns a plain relative
 *                          `/api/media/<key>` path — same-origin, so it
 *                          works regardless of domain and never needs a
 *                          localhost/production fallback at all.
 *   S3_PUBLIC_URL          Legacy-only: previously used as a *direct*
 *                          browser-facing MinIO URL. No longer used to
 *                          build new URLs (see getPublicUrl), but still
 *                          recognized by extractKeyFromPublicUrl() so
 *                          invites created before this change keep working.
 */

import {
  S3Client,
  PutObjectCommand,
  DeleteObjectCommand,
  CopyObjectCommand,
  HeadObjectCommand,
  GetObjectCommand,
  ListObjectsV2Command,
} from "@aws-sdk/client-s3";

export interface UploadParams {
  key: string;
  contentType: string;
  body: Buffer | Uint8Array;
}

export function getStorageConfig() {
  return {
    endpoint: process.env.S3_ENDPOINT ?? "",
    bucket: process.env.S3_BUCKET ?? "invitesaas",
    region: process.env.S3_REGION ?? "us-east-1",
    accessKey: process.env.S3_ACCESS_KEY ?? "",
    secretKey: process.env.S3_SECRET_KEY ?? "",
    publicUrl: process.env.S3_PUBLIC_URL ?? "",
  };
}

export function isStorageConfigured(): boolean {
  const cfg = getStorageConfig();
  return Boolean(cfg.endpoint && cfg.accessKey && cfg.secretKey);
}

let client: S3Client | null = null;
function getClient(): S3Client {
  if (client) return client;
  const cfg = getStorageConfig();
  client = new S3Client({
    endpoint: cfg.endpoint,
    region: cfg.region,
    credentials: { accessKeyId: cfg.accessKey, secretAccessKey: cfg.secretKey },
    forcePathStyle: true,
  });
  return client;
}

/** Upload a file to S3/MinIO and return its public URL. */
export async function uploadFile(params: UploadParams): Promise<string> {
  if (!isStorageConfigured()) {
    throw new Error(
      "Storage is not configured. Set S3_ENDPOINT, S3_ACCESS_KEY, S3_SECRET_KEY in .env"
    );
  }
  const cfg = getStorageConfig();
  await getClient().send(
    new PutObjectCommand({
      Bucket: cfg.bucket,
      Key: params.key,
      Body: params.body,
      ContentType: params.contentType,
    })
  );
  return getPublicUrl(params.key);
}

export async function deleteFile(key: string): Promise<void> {
  if (!isStorageConfigured()) return;
  const cfg = getStorageConfig();
  await getClient().send(new DeleteObjectCommand({ Bucket: cfg.bucket, Key: key }));
}

/**
 * Copies an object to a new key and deletes the original. Used to move
 * anonymous temp uploads (temp/<draftToken>/...) into an invite's own
 * namespace once the invite is claimed by an authenticated user.
 */
export async function moveFile(fromKey: string, toKey: string): Promise<string> {
  if (!isStorageConfigured()) {
    throw new Error("Storage is not configured.");
  }
  const cfg = getStorageConfig();
  const client = getClient();
  await client.send(
    new CopyObjectCommand({
      Bucket: cfg.bucket,
      CopySource: `/${cfg.bucket}/${fromKey}`,
      Key: toKey,
    })
  );
  await client.send(new DeleteObjectCommand({ Bucket: cfg.bucket, Key: fromKey }));
  return getPublicUrl(toKey);
}

export interface ObjectMeta {
  size: number;
  contentType?: string;
  etag?: string;
  lastModified?: Date;
}

export async function statFile(key: string): Promise<ObjectMeta | null> {
  if (!isStorageConfigured()) return null;
  try {
    const cfg = getStorageConfig();
    const res = await getClient().send(new HeadObjectCommand({ Bucket: cfg.bucket, Key: key }));
    return {
      size: res.ContentLength ?? 0,
      contentType: res.ContentType,
      etag: res.ETag,
      lastModified: res.LastModified,
    };
  } catch {
    return null;
  }
}

export interface ObjectStream extends ObjectMeta {
  stream: ReadableStream;
}

function isNotFoundError(err: unknown): boolean {
  const name = (err as { name?: string } | undefined)?.name;
  const status = (err as { $metadata?: { httpStatusCode?: number } } | undefined)?.$metadata?.httpStatusCode;
  return name === "NoSuchKey" || name === "NotFound" || status === 404;
}

/**
 * Opens a readable stream for an object's body — used by the /api/media
 * proxy to relay S3/MinIO content to the browser without buffering the
 * whole file in memory. Returns null for a missing object (caller returns
 * 404); rethrows anything else (caller returns a generic 502).
 */
export async function getObjectStream(key: string): Promise<ObjectStream | null> {
  if (!isStorageConfigured()) return null;
  const cfg = getStorageConfig();
  try {
    const res = await getClient().send(new GetObjectCommand({ Bucket: cfg.bucket, Key: key }));
    if (!res.Body) return null;
    return {
      stream: res.Body.transformToWebStream(),
      size: res.ContentLength ?? 0,
      contentType: res.ContentType,
      etag: res.ETag,
      lastModified: res.LastModified,
    };
  } catch (err) {
    if (isNotFoundError(err)) return null;
    throw err;
  }
}

export interface StoredObject {
  key: string;
  lastModified: Date | null;
  size: number;
}

/**
 * Lists every object under `prefix` (paginated internally). Used by the
 * anonymous-upload cleanup job to scan temp/ — never call this with an
 * empty/unbounded prefix in that context, since it would enumerate the
 * whole bucket including invites/* permanent media.
 */
export async function listObjectsUnderPrefix(prefix: string): Promise<StoredObject[]> {
  if (!isStorageConfigured()) return [];
  const cfg = getStorageConfig();
  const client = getClient();
  const results: StoredObject[] = [];
  let continuationToken: string | undefined;

  do {
    const res = await client.send(
      new ListObjectsV2Command({
        Bucket: cfg.bucket,
        Prefix: prefix,
        ContinuationToken: continuationToken,
        MaxKeys: 1000,
      })
    );
    for (const obj of res.Contents ?? []) {
      if (!obj.Key) continue;
      results.push({ key: obj.Key, lastModified: obj.LastModified ?? null, size: obj.Size ?? 0 });
    }
    continuationToken = res.IsTruncated ? res.NextContinuationToken : undefined;
  } while (continuationToken);

  return results;
}

/** Encodes each path segment individually so "/" separators survive. */
function encodeObjectKey(key: string): string {
  return key.split("/").map(encodeURIComponent).join("/");
}

/** Inverse of encodeObjectKey — safe even if the input has no encoding to undo. */
function decodeObjectKey(encoded: string): string {
  try {
    return encoded.split("/").map(decodeURIComponent).join("/");
  } catch {
    return encoded;
  }
}

/**
 * Browser-facing URL for an object: a same-origin `/api/media/<key>` path
 * served by src/app/api/media/[...key]/route.ts. S3_ENDPOINT is internal
 * (e.g. Coolify's private MinIO service address) and must never reach the
 * browser directly — this is the one function anything client-visible
 * should call to point at a stored object.
 *
 * Deliberately relative (no origin) unless MEDIA_PUBLIC_BASE_URL is set:
 * a relative path resolves correctly regardless of what domain the app is
 * served from, so there's no localhost/production-origin fallback to get
 * wrong, and a future domain change never requires rewriting stored URLs.
 */
export function getPublicUrl(key: string): string {
  const path = `/api/media/${encodeObjectKey(key)}`;
  const base = process.env.MEDIA_PUBLIC_BASE_URL;
  return base ? `${base.replace(/\/$/, "")}${path}` : path;
}

/**
 * Resolves a value that might be either a storage key (the current upload
 * flow) or an already-usable URL (legacy admin-pasted external link, from
 * before an upload UI existed for that field) into something a browser can
 * load directly. Needed for fields like InviteTemplate.previewImage/
 * demoImage that predate their own upload UI and may still hold raw URLs.
 */
export function resolveStoredImage(value: string | null | undefined): string | null {
  if (!value) return null;
  if (/^https?:\/\//i.test(value) || value.startsWith("/")) return value;
  return getPublicUrl(value);
}

/**
 * Inverse of getPublicUrl. Recognizes two formats so already-stored data
 * keeps working across this change:
 *   A) current:  <anything>/api/media/<encoded-key>  — matched by the
 *      `/api/media/` marker alone, independent of host, so it survives the
 *      app moving domains or MEDIA_PUBLIC_BASE_URL changing later.
 *   B) legacy:   <S3_PUBLIC_URL-or-S3_ENDPOINT>/<bucket>/<key> — URLs
 *      generated before this proxy existed.
 */
export function extractKeyFromPublicUrl(url: string): string | null {
  if (!url) return null;
  const withoutQuery = url.split(/[?#]/, 1)[0] ?? url;

  const proxyMarker = "/api/media/";
  const proxyIdx = withoutQuery.indexOf(proxyMarker);
  if (proxyIdx !== -1) {
    const encodedKey = withoutQuery.slice(proxyIdx + proxyMarker.length);
    return encodedKey ? decodeObjectKey(encodedKey) : null;
  }

  const { endpoint, bucket, publicUrl } = getStorageConfig();
  for (const base of [publicUrl, endpoint]) {
    if (!base) continue;
    const prefix = `${base.replace(/\/$/, "")}/${bucket}/`;
    if (withoutQuery.startsWith(prefix)) {
      const key = withoutQuery.slice(prefix.length);
      return key || null;
    }
  }

  return null;
}
